table dVendedor
	lineageTag: 4912122d-431e-4847-a272-59351ed8bc52

	column Colaborador_ID
		dataType: int64
		formatString: 0
		lineageTag: 6532e412-dbc6-40e4-aac9-b587c4eaeec8
		summarizeBy: none
		sourceColumn: Colaborador_ID

		annotation SummarizationSetBy = Automatic

	column Loja_ID
		dataType: int64
		formatString: 0
		lineageTag: ee091622-9dba-4bc9-b0fa-f38b73402e0f
		summarizeBy: none
		sourceColumn: Loja_ID

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: fe511e58-208c-4e30-8443-7462ec56cea8
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Função
		dataType: string
		lineageTag: ba80c2e7-de72-4a8f-8957-12b955749bfa
		summarizeBy: none
		sourceColumn: Função

		annotation SummarizationSetBy = Automatic

	column 'Horas Trabalhadas Semanais'
		dataType: int64
		formatString: 0
		lineageTag: 0dfb560c-6828-4b2b-8e7e-f60da8a3f0b1
		summarizeBy: none
		sourceColumn: Horas Trabalhadas Semanais

		annotation SummarizationSetBy = Automatic

	column 'Avaliação de Desempenho'
		dataType: double
		lineageTag: 0d0b0beb-f10c-4b94-b427-35e4f77992f5
		summarizeBy: none
		sourceColumn: Avaliação de Desempenho

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Vendas Realizadas'
		dataType: int64
		formatString: 0
		lineageTag: 21776f76-73ed-4c1e-914e-6d5b2a48874d
		summarizeBy: none
		sourceColumn: Vendas Realizadas

		annotation SummarizationSetBy = Automatic

	column Naturalidade
		dataType: string
		lineageTag: 0d861f44-24af-4033-af9a-a16d3e0800a1
		summarizeBy: none
		sourceColumn: Naturalidade

		annotation SummarizationSetBy = Automatic

	column Imagem
		dataType: string
		lineageTag: fb0ce736-6708-4243-a934-193c9c098913
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Imagem

		annotation SummarizationSetBy = Automatic

	partition dVendedor = m
		mode: import
		queryGroup: Dimensões
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/Ricardo-Filgueiras/Analise-Business-Intelligence/refs/heads/main/src/dados/Colaboradores.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Promoted Headers", {{"Avaliação de Desempenho", type number}}, "en-US"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type with Locale",{{"Colaborador_ID", Int64.Type}, {"Loja_ID", Int64.Type}, {"Nome", type text}, {"Função", type text}, {"Horas Trabalhadas Semanais", Int64.Type}, {"Avaliação de Desempenho", type number}, {"Vendas Realizadas", Int64.Type}, {"Naturalidade", type text}, {"Imagem", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

