table Medidas
	lineageTag: 8714e66e-a7e8-4f65-95dd-41d8bee6af7d

	measure faturamento = ```
			
			SUMX(
			    fVendas,
			    fVendas[Quantidade] * fVendas[Preço Unitário] 
			)
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 628db457-6eca-4814-af94-655f56bb2777

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Qtde Venda' = DISTINCTCOUNT( fVendas[Venda_ID] )
		formatString: 0
		lineageTag: 78d7a339-46ed-4648-88df-6a66c397a565

	column 'Coluna 1'
		dataType: string
		isHidden
		lineageTag: 576677e2-20a4-4226-b0f1-ac4805e3c1d1
		summarizeBy: none
		sourceColumn: Coluna 1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Medidas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t])
				in
				    Source

	annotation PBI_ResultType = Table

